version: '3.8'

services:

  db:
    image: postgres:16
    container_name: MDMA_postgres_dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: MDMA_keycloak_dev
    command: start-dev --import-realm
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/dev-realm.json
    volumes:
      - ./docker/keycloak:/opt/keycloak/data/import
      - keycloak-data:/opt/keycloak/data

volumes:
  db-data:
  keycloak-data:
