FROM node:23-alpine
WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci

ENV PATH /app/node_modules/.bin:$PATH

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--poll", "500"] 