openapi: 3.0.0
info:
  title: MDMA_API
  version: 1.0.0
servers:
  - url: http://localhost:9090/api
paths:
  /user/me:
    get:
      tags:
        - User
      operationId: getCurrentUser
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        firstName:
          type: string
        lastName:
          type: string
      required: [id, username, email]